---
- name: Playbook with customizable port
  hosts: all
  vars:
    ansible_ssh_port: "{{ port }}"
    ansible_ssh_user: "{{ user }}"
    ansible_ssh_pass: "{{ password }}"
  tasks:
    - name: Task 1
      debug:
        msg: "Using port {{ port }}, user {{ user }} & password {{ password }}"
